### ISSUE TITLE
Add queue classic

### ISSUE THREAD

**Issue by ericboehs** [brightbit/rails-template#8]
See https://github.com/brightbit/rails-template/tree/8-add_queue_classic and https://github.com/brightbit/rails-template/commit/c7ce43db9fa9c289c1727e0d9bac0f34dc6f6f07

**Comment by jcamenisch** [comment]
Thanks for taking care of this, @ericboehs

**Comment by ericboehs** [comment]
Yep yep. Bunch of other goodies in master too. Check em out :)

**Comment by jcamenisch** [comment]
Yah. I'm trying to figure out how to rebase Soundingboard onto this. I left
it in a state where mailers weren't quite working, so this would hopefully
get me past that, along with the other good stuff.
